/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.assertEquals;

public class AppTest {
  @Test
  public void testBook(){
      App app=new App();
      try {
          assertEquals("quotes.Qoute", app.randomBook("src\\main\\resources\\recentquotes.json").getClass().getName());
      } catch (FileNotFoundException e) {
          e.printStackTrace();
      }

  }
    @Test public void testGetRandomQuote() throws FileNotFoundException {
        App classUnderTest = new App();
        Qoute quote = classUnderTest.randomBook("src\\main\\resources\\recentquotes.json");
        assertEquals("Test the Type Of the Output of getQuote Method", true, quote instanceof Qoute);
        assertEquals("The first part of the output","The quote is",quote.toString().split(":")[0]);
        assertEquals("The text of the quote != null",false,quote.toString().split(":")[1] == null);
    }
}
