/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.assertEquals;

public class AppTest {
  @Test
  public void testBook(){
      App app=new App();
      try {
          assertEquals("java.lang.String", app.randomBook("src\\main\\resources\\recentquotes.json").getClass().getName());
      } catch (FileNotFoundException e) {
          e.printStackTrace();
      }

  }
}
