/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

public class App {

    public static void main(String[] args) throws FileNotFoundException {

        System.out.println(randomBook("app/src/main/resources/recentquotes.json"));
        randomBook("app/src/main/resources/recentquotes.json");

    }
    public static Qoute randomBook(String path) throws FileNotFoundException {
        Gson gson=new Gson();
        Reader reader = new FileReader(path);
        Contact[] book = gson.fromJson(reader, Contact[].class);
        int rand= (int) (Math.random()*book.length);
        Qoute qoute=new Qoute(book[rand]);
        return qoute;
    }
}
